### PR TITLE
add get method that returns the subject

### PR DESCRIPTION
**Pull request by christophsturm**

### CODE REVIEW

**Comment by dave08** [comment]
Isn't this already possible with `and { }`? And doing `expectThat(subject.name)...` looks a bit simpler?

**Comment by christophsturm** [comment]
the use case is to split big expectThat block into smaller blocks.
and to simplify code like this: 
```
                describe("get routes") {
                    expectThat(routes).getValue(Method.GET).hasSize(2)
                    val getRoutes = routes[Method.GET]!!
                    it("adds a get detail route") {
```

to 
`val getRoutes= expectThat(routes).getValue(Method.GET).hasSize(2).get()`

**Comment by dave08** [comment]
Oh! An expect in `describe`, that seems to not conform with AAA (Arrange Act Assert)? I usually have them only in `it` blocks... then asserting deeper is easier with `and { }`. And anyways after a bit more chaining, it can get confusing to see what that's actually returning... but I see the point a bit better now.

**Comment by christophsturm** [comment]
well in failfast there is no strict separation between contexts and tests, so you can put asserts in the context, if it fails the context counts as 1 failed test. and in the child tests you then assert more on specifics for that one property that the test asserts.

the main point of the new `get()` method is to make it possible to use strikt to safely navigate object graphs.

**Comment by robfletcher** [comment]
I think this is a pretty radical change to Strikt's encapsulation. In some ways it would make writing tests with Strikt vastly easier because there would just be no need for all the mapping functions. At that point I wonder if we're talking about a different assertion library, though.

**Pull request closed without merging**
